### ISSUE TITLE
Mobile: footer

### ISSUE THREAD

**Issue by marceloglacial** [marceloglacial/2021-leal-e-clementino#21]

**Comment by dutraneto** [comment]
Question: does the footer goes aligned center on ipads like this

<img width="484" alt="Screen Shot 2021-03-04 at 2 50 30 PM" src="https://user-images.githubusercontent.com/18724070/110022632-289d5580-7cfa-11eb-9747-4a68b0b40a60.png">

or

it should maintain the left padding of the design?

![Screen Shot 2021-03-04 at 2 49 01 PM](https://user-images.githubusercontent.com/18724070/110022579-14595880-7cfa-11eb-9e9a-571efa9ef4e6.png)

**Comment by marceloglacial** [comment]
> Question: does the footer goes aligned center on ipads like this
> 
> <img alt="Screen Shot 2021-03-04 at 2 50 30 PM" width="484" src="https://user-images.githubusercontent.com/18724070/110022632-289d5580-7cfa-11eb-9747-4a68b0b40a60.png">
> 
> or
> 
> it should maintain the left padding of the design?
> 
> ![Screen Shot 2021-03-04 at 2 49 01 PM](https://user-images.githubusercontent.com/18724070/110022579-14595880-7cfa-11eb-9e9a-571efa9ef4e6.png)

Left
