### ISSUE TITLE
Mobile: Header

### ISSUE THREAD

**Issue by marceloglacial** [marceloglacial/2021-leal-e-clementino#23]
iPad portrait = phone
iPad landscape = desktop

**Comment by marceloglacial** [comment]
Please follow the designs proportions. 
Logo is not centralized and the icon is too small.

<img width="1792" alt="Screen Shot 2021-03-03 at 8 10 54 AM" src="https://user-images.githubusercontent.com/11657599/109811391-c7418d80-7bf8-11eb-86c5-7add229a2143.png">
<img width="559" alt="Screen Shot 2021-03-03 at 8 11 12 AM" src="https://user-images.githubusercontent.com/11657599/109811403-c90b5100-7bf8-11eb-8f08-5198a2e8f4ac.png">

**Comment by dutraneto** [comment]
Understood!
