### ISSUE TITLE
Section Height breaking the sidebar

### ISSUE THREAD

**Issue by marceloglacial** [marceloglacial/2021-leal-e-clementino#41]
How do reproduce: 

Click on any nav item besides "Quem Somos" and click back to "Quem Somos"

<img width="1107" alt="Screen Shot 2021-03-09 at 8 34 10 AM" src="https://user-images.githubusercontent.com/11657599/110478592-804d0f80-80b2-11eb-98a0-0e2a133a518e.png">
<img width="1481" alt="Screen Shot 2021-03-09 at 8 33 56 AM" src="https://user-images.githubusercontent.com/11657599/110478596-804d0f80-80b2-11eb-8d4c-306e35389bd6.png">

**Comment by dutraneto** [comment]
this is happening because I changed the height from 100vh to auto. I'll get back to its initial value
