### ISSUE TITLE
iPad (Portrait) - Left/Right Margins

### ISSUE THREAD

**Issue by marceloglacial** [marceloglacial/2021-leal-e-clementino#47]
Please make the content margins align to the logo margin

<img width="922" alt="Screen Shot 2021-03-09 at 9 34 37 PM" src="https://user-images.githubusercontent.com/11657599/110567468-9218cc00-811f-11eb-88a1-214ee183ae70.png">

**Comment by dutraneto** [comment]
<img display="inline" width="413" alt="Screen Shot 2021-03-11 at 7 54 26 AM" src="https://user-images.githubusercontent.com/18724070/110791145-ddc29700-823f-11eb-9ca8-b8692daa9f76.png">
<img display="inline" width="413" alt="Screen Shot 2021-03-11 at 7 56 24 AM" src="https://user-images.githubusercontent.com/18724070/110791154-e024f100-823f-11eb-9f95-cab19162845c.png">
<img width="673" alt="PixelSnap 2021-03-11 at 07 59 43@2x" src="https://user-images.githubusercontent.com/18724070/110791169-e5823b80-823f-11eb-81ab-aa320d9b7447.png">

**Comment by dutraneto** [comment]
1. Should I increase margins for tablets? (How much?)
2. Should I make even for both sides? (46 or 39?)
3. I can set different margins for phones (2rem=32px) and (2.5rem=40px). This will afect a lot in our design right now, but it could be done.

**Comment by marceloglacial** [comment]
> 1. Should I increase margins for tablets? (How much?)
> 2. Should I make even for both sides? (46 or 39?)
> 3. I can set different margins for phones (2rem=32px) and (2.5rem=40px). This will afect a lot in our design right now, but it could be done.

Please make it 2rem for phones and 2.5rem for tablet portrait.

**Comment by dutraneto** [comment]
Will do
