### ISSUE TITLE
Smooth scrolling does not work in Safari

### ISSUE THREAD

**Issue by dutraneto** [marceloglacial/2021-leal-e-clementino#55]
I've done a couple of tests with different browsers.
At this moment, Safari does not support smooth scroll. That said, I'd suggest 3 alternatives:

1. Adding a [polyfill](http://iamdustan.com/smoothscroll/).
2. Adding [jQuery](https://jquery.com/) (which I would personally choose due to my familiarity with it and I've done it several times in my personal projects).
3. Adding another smooth scroll library that I am 100% sure will use jQuery due to its popularity.

What that sound like to you?

**Comment by marceloglacial** [comment]
No jQuery please.
